-- MySQL Script generated by MySQL Workbench
-- 04/20/16 00:53:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SandBoxLearn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SandBoxLearn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SandBoxLearn` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `SandBoxLearn` ;


-- -----------------------------------------------------
-- Table `SandBoxLearn`.`tb_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SandBoxLearn`.`tb_list` ;

CREATE TABLE IF NOT EXISTS `SandBoxLearn`.`tb_list` (
  `ID_list` INT NOT NULL,
  `list_name` VARCHAR(45) NOT NULL,
  `list_description` TEXT(200) NULL,
  `list_commentary` TEXT(200) NULL,
  `list_difficulty` INT NULL,
  `user_ID_Utilisateur` INT NOT NULL,
  PRIMARY KEY (`ID_list``),
  INDEX `fk_list_user1_idx` (`user_ID_Utilisateur` ASC),
  CONSTRAINT `fk_list_user1`
    FOREIGN KEY (`user_ID_Utilisateur`)
    REFERENCES `SandBoxLearn`.`tb_user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SandBoxLearn`.`tb_list_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SandBoxLearn`.`tb_list_question` ;

CREATE TABLE IF NOT EXISTS `SandBoxLearn`.`tb_list_question` (
  `list_ID_list` INT NOT NULL,
  `question_ID_question` INT NOT NULL,
  PRIMARY KEY (`list_ID_list`, `question_ID_question`),
  INDEX `fk_list_has_Question_Question1_idx` (`question_ID_question` ASC),
  INDEX `fk_list_has_Question_list1_idx` (`list_ID_list` ASC),
  CONSTRAINT `fk_list_has_Question_list1`
    FOREIGN KEY (`list_ID_list`)
    REFERENCES `SandBoxLearn`.`tb_list` (`ID_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_has_Question_Question1`
    FOREIGN KEY (`question_ID_question`)
    REFERENCES `SandBoxLearn`.`tb_question` (`ID_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SandBoxLearn`.`tb_masteries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SandBoxLearn`.`tb_masteries` ;

CREATE TABLE IF NOT EXISTS `SandBoxLearn`.`tb_masteries` (
  `user_ID_Utilisateur` INT NOT NULL,
  `question_ID_Question` INT NOT NULL,
  `level` INT NULL,
  `last_answer` TINYINT(1) NULL,
  PRIMARY KEY (`user_ID_Utilisateur`, `question_ID_Question`),
  INDEX `fk_user_has_Question_Question1_idx` (`question_ID_Question` ASC),
  INDEX `fk_user_has_Question_user1_idx` (`user_ID_Utilisateur` ASC),
  CONSTRAINT `fk_user_has_Question_user1`
    FOREIGN KEY (`user_ID_Utilisateur`)
    REFERENCES `SandBoxLearn`.`tb_user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_Question_Question1`
    FOREIGN KEY (`question_ID_Question`)
    REFERENCES `SandBoxLearn`.`tb_question` (`ID_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SandBoxLearn`.`tb_list_workout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SandBoxLearn`.`tb_list_workout` ;

CREATE TABLE IF NOT EXISTS `SandBoxLearn`.`tb_list_workout` (
  `user_ID_user` INT NOT NULL,
  `list_ID_list` INT NOT NULL,
  PRIMARY KEY (`user_ID_user`, `list_ID_list`),
  INDEX `fk_user_has_list_list1_idx` (`list_ID_list` ASC),
  INDEX `fk_user_has_list_user1_idx` (`user_ID_user` ASC),
  CONSTRAINT `fk_user_has_list_user1`
    FOREIGN KEY (`user_ID_user`)
    REFERENCES `SandBoxLearn`.`tb_user` (`ID_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_list_list1`
    FOREIGN KEY (`list_ID_list`)
    REFERENCES `SandBoxLearn`.`tb_list` (`ID_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SandBoxLearn`.`tb_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SandBoxLearn`.`tb_tag` ;

CREATE TABLE IF NOT EXISTS `SandBoxLearn`.`tb_tag` (
  `ID_tag` INT NOT NULL,
  `tag` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SandBoxLearn`.`tb_list_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SandBoxLearn`.`tb_list_tag` ;

CREATE TABLE IF NOT EXISTS `SandBoxLearn`.`tb_list_tag` (
  `list_ID_list` INT NOT NULL,
  `tag_ID_tag` INT NOT NULL,
  PRIMARY KEY (`list_ID_list`, `tag_ID_tag`),
  INDEX `fk_list_has_tag_tag1_idx` (`tag_ID_tag` ASC),
  INDEX `fk_list_has_tag_list1_idx` (`list_ID_list` ASC),
  CONSTRAINT `fk_list_has_tag_list1`
    FOREIGN KEY (`list_ID_list`)
    REFERENCES `SandBoxLearn`.`tb_list` (`ID_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_list_has_tag_tag1`
    FOREIGN KEY (`tag_ID_tag`)
    REFERENCES `SandBoxLearn`.`tb_tag` (`ID_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SandBoxLearn`.`tb_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SandBoxLearn`.`tb_question` ;

CREATE TABLE IF NOT EXISTS `SandBoxLearn`.`tb_question` (
  `ID_Question` INT(11) NOT NULL AUTO_INCREMENT,
  `Question` VARCHAR(140) NOT NULL,
  `Answer` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`ID_Question`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SandBoxLearn`.`tb_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SandBoxLearn`.`tb_user` ;

CREATE TABLE IF NOT EXISTS `SandBoxLearn`.`tb_user` (
  `ID_User` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_User`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
